import type { CollectionConfig } from 'payload'
export const HeroSlides: CollectionConfig = {
  slug: 'hero-slides',
  admin: { useAsTitle: 'headline', defaultColumns: ['headline','type','order','active'] },
  fields: [
    { name: 'type', type: 'select', label: 'Tip', required: true, defaultValue: 'video',
      options: [{ label: 'Video', value: 'video' },{ label: 'Imagine', value: 'image' }] },
    { name: 'videoFile', type: 'upload', relationTo: 'media', label: 'Video MP4',
      admin: { condition: (d) => d?.type === 'video' } },
    { name: 'image', type: 'upload', relationTo: 'media', label: 'Imagine',
      admin: { condition: (d) => d?.type === 'image' } },
    { name: 'posterImage', type: 'upload', relationTo: 'media', label: 'Poster fallback',
      admin: { condition: (d) => d?.type === 'video' } },
    { name: 'subtitle', type: 'text', label: 'Subtitlu' },
    { name: 'headline', type: 'text', label: 'Titlu principal', required: true },
    { name: 'description', type: 'textarea', label: 'Descriere' },
    { name: 'ctaPrimaryText', type: 'text', label: 'CTA 1 — text',
      admin: { description: 'Textul butonului principal. Ex: „Solicita oferta"' } },
    { name: 'ctaPrimaryUrl', type: 'text', label: 'CTA 1 — link',
      admin: { placeholder: '/contact', description: 'Pagina catre care duce butonul. Foloseste calea relativa, ex: /contact, /proiecte, /despre' } },
    { name: 'ctaSecondaryText', type: 'text', label: 'CTA 2 — text',
      admin: { description: 'Textul butonului secundar. Ex: „Vezi proiecte"' } },
    { name: 'ctaSecondaryUrl', type: 'text', label: 'CTA 2 — link',
      admin: { placeholder: '/proiecte', description: 'Pagina catre care duce butonul. Foloseste calea relativa, ex: /contact, /proiecte, /despre' } },
    { name: 'order', type: 'number', label: 'Ordine', required: true, defaultValue: 1, admin: { position: 'sidebar' } },
    { name: 'active', type: 'checkbox', label: 'Activ', defaultValue: true, admin: { position: 'sidebar' } },
  ],
}
